name: update reactions

on:
  workflow_dispatch:
  schedule:
    - cron: "42 23 * * *"

jobs:
  update_reactions:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          cache: "pip"
          cache-dependency-path: "requirements.txt"
      - name: run python
        run: |
          pip install -r requirements.txt
          python main.py -a ${{ secrets.YT_API_KEY }}
      - name: commit files
        run: |
          if [ $(git status -s | wc -l) == 0 ]; then exit 0; fi
          git config --global user.name 'gh-actions'
          git config --global user.email 'seriousm4x@users.noreply.github.com'
          git add .
          git commit -m "workflow update ($(date +'%Y.%m.%d %H:%M:%S'))"
          git push
